FROM mcr.microsoft.com/playwright:v1.44.0-jammy
WORKDIR /app

# Копируем package.json и package-lock.json из папки mobile_tests
COPY ../package*.json ./

RUN npm ci

# Копируем все тесты мобильной версии
COPY ../ ./

RUN npx playwright install --with-deps

CMD ["npx", "playwright", "test", "mobile_tests"]

