name: Run Tests Separately

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Playwright Docker image
        run: docker build -f Dockerfile.playwright -t playwright-tests .
      - name: Run Playwright tests
        run: docker run --rm playwright-tests

  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build k6 Docker image
        run: docker build -f Dockerfile.k6 -t k6-tests .
      - name: Run k6 tests
        run: docker run --rm k6-tests
