name: Run K6 Load Test in Docker

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t k6-load-test .

      - name: Run K6 Load Test
        run: docker run --rm k6-load-test
