name: Full Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [desktop, mobile, k6]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t full-test-suite -f ./tests/DOCKER/Dockerfile .

      - name: Run Tests
        run: |
          if [ "${{ matrix.type }}" == "desktop" ]; then
            docker run --rm full-test-suite npx playwright test --project=desktop
          elif [ "${{ matrix.type }}" == "mobile" ]; then
            docker run --rm full-test-suite npx playwright test --project=mobile
          elif [ "${{ matrix.type }}" == "k6" ]; then
            docker run --rm full-test-suite k6 run ./tests/load/test.js
          fi
