name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-tests ./tests/DOCKER

      - name: Run Playwright tests (Desktop + Mobile)
        run: docker run --rm my-tests npx playwright test

      - name: Run k6 tests
        run: docker run --rm my-tests k6 run ./tests/k6/test.js
