name: Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2. Ставим Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker для Playwright
      - name: Build Playwright Docker
        run: docker build -t playwright-tests D:/Playwright_Automation/tests/DOCKER

      # 4. Run Playwright тесты (Desktop)
      - name: Run Desktop Tests
        run: docker run --rm playwright-tests npm run test:desktop

      # 5. Run Playwright тесты (Mobile)
      - name: Run Mobile Tests
        run: docker run --rm playwright-tests npm run test:mobile

      # 6. Run k6 тесты (используем официальный образ)
      - name: Run k6 Load Tests
        run: docker run --rm -v D:/Playwright_Automation/tests/load:/tests loadimpact/k6 run /tests/test.js
