name: Run Playwright & K6 Tests

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Какие тесты запускать"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - mobile
          - desktop
          - k6
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mobile-tests:
    if: github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright Mobile Tests
        run: npx playwright test ./tests/mobile_tests

  desktop-tests:
    if: github.event.inputs.target == 'all' || github.event.inputs.target == 'desktop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright Desktop Tests
        run: npx playwright test ./tests/desktop_tests

  k6-tests:
    if: github.event.inputs.target == 'all' || github.event.inputs.target == 'k6'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t k6-load-test -f ./tests/DOCKER/Dockerfile .

      - name: Run K6 Load Tests
        run: docker run --rm k6-load-test k6 run ./tests/k6_tests/scripts/first.load.test.js
